In [2]:
import numpy as np

In [3]:
# Catálogo
# [vCPUs, RAM (GB), SSD (GB)]
catalogo_servidores = np.array([
    [2.0, 4.0, 50.0],
    [4.0, 8.0, 100.0],
    [8.0, 16.0, 250.0],
    [16.0, 32.0, 500.0],
    [32.0, 64.0, 1000.0],
    [64.0, 128.0, 2000.0]
])

# Nomes comerciais
nomes_servidores = [
    "Micro Instância Web",
    "Standard App Server",
    "Medium Backend & Cache",
    "Database Enterprise",
    "High Performance Computing",
    "Big Data & AI Training"
]

print("=== CATÁLOGO DE SERVIDORES ===")
print(catalogo_servidores)

=== CATÁLOGO DE SERVIDORES ===
[[   2.    4.   50.]
 [   4.    8.  100.]
 [   8.   16.  250.]
 [  16.   32.  500.]
 [  32.   64. 1000.]
 [  64.  128. 2000.]]


In [4]:
# Requisitos da aplicação
perfil_demandado = np.array([12.0, 28.0, 850.0])

# Quantidade de recomendações
k = 2

In [5]:
# Função de recomendação
def recomendar_servidores(catalogo, perfil, k):

    # Calcula as distâncias de forma vetorizada
    distancias = np.sqrt(
        np.sum((catalogo - perfil) ** 2, axis=1)
    )

    # Ordena pela menor distância
    indices_ordenados = np.argsort(distancias)

    # Seleciona as melhores recomendações
    indices_recomendados = indices_ordenados[:k]

    return indices_recomendados, distancias[indices_recomendados]

In [6]:
# Executa a recomendação
indices_recomendados, distancias_recomendadas = recomendar_servidores(
    catalogo_servidores,
    perfil_demandado,
    k
)

In [7]:
# Exibe o ranking
print("=== RANKING DE SERVIDORES RECOMENDADOS ===")

for posicao, (indice, distancia) in enumerate(
    zip(indices_recomendados, distancias_recomendadas),
    start=1
):

    servidor = catalogo_servidores[indice]
    nome = nomes_servidores[indice]

    print(f"\n{posicao}º lugar - {nome}")
    print(f"vCPUs: {servidor[0]:.0f}")
    print(f"RAM: {servidor[1]:.0f} GB")
    print(f"SSD: {servidor[2]:.0f} GB")
    print(f"Distância: {distancia:.2f}")

=== RANKING DE SERVIDORES RECOMENDADOS ===

1º lugar - High Performance Computing
vCPUs: 32
RAM: 64 GB
SSD: 1000 GB
Distância: 155.55

2º lugar - Database Enterprise
vCPUs: 16
RAM: 32 GB
SSD: 500 GB
Distância: 350.05
